greet :
	@echo "hii"
say_hello :
	@echo "hello"
create :
	@echo "creating files"
	@touch pqr.txt
	touch rst.txt
.DEFAULT_GOAL := create
remove :
	@echo "deleting files"
	rm rst.txt	
copy :
	@echo "copying files"
	cp abc.txt xyz.txt
all : greet create copy remove 

